version: '3.9'
services:
  api:
    build: ../..
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    networks:
      - glimpse_network
    profiles:
      - api
    depends_on:
      - db
      - redis
      - rabbitmq

  api-production:
    image: ghcr.io/rpitv/glimpse-api:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    networks:
      - glimpse_network
    profiles:
      - production
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - .db-data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    networks:
      - glimpse_network

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - .redis-data:/data
    networks:
      - glimpse_network

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - glimpse_network

networks:
  glimpse_network:
    name: glimpse_network
